import express from 'express';
import cors from 'cors';
import router from './routes/urlRoutes.mjs';
import  errorHandler from './middleware/errorHandler.mjs';
const app = express();
app.use(cors());
app.use(express.json());
app.use('/', router);
app.use(errorHandler);
export default app;